name: Dumortierite
version: 0.1.0
author: Sapphira Tempest
description: A Slimefun4 addon that add some useful gadgets.
website: https://github.com/freeze-dolphin/Dumortierite

main: io.sn.dumortierite.DumoCore
depend:
  - Slimefun
  - NBTAPI

softdepend:
  - ItemsAdder

api-version: 1.19

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.7.10
  - net.kyori:adventure-text-minimessage:4.13.1
  - org.apache.groovy:groovy-jsr223:4.0.12
  - org.clojure:clojure:1.11.1
