info:
  namespace: dumortierite
font_images:
  blank:
    path: gui/blank
    suggest_in_command: false
    y_position: 0
  coal_generator:
    path: gui/coal_generator
    suggest_in_command: false
    y_position: 12
  biomass_generator:
    path: gui/biomass_generator
    suggest_in_command: false
    y_position: 12
